metabrainz/acousticbrainz-server

templates/data.html

Fixed link to sample data

---

acousticbrainz/views/data.py
templates/data/json-display.html

*Fixes http://tickets.musicbrainz.org/browse/AB-24.*

AB-24: Links back to summary page from JSON view

---

acousticbrainz/data/__init__.py
acousticbrainz/views/api.py

Since we don't have a way to order data by it's "goodness", there's no selection of the best dataset. First one is returned if there's no offset.
*Fixes http://tickets.musicbrainz.org/browse/AB-11.*

AB-11: Duplicate data fetching

---

INSTALL.md
README.md
acousticbrainz/data/__init__.py
acousticbrainz/data/dump.py
acousticbrainz/data/dump_manager.py
acousticbrainz/testing.py
high-level/hl_calc.py
templates/data/data.html
templates/data/summary.html
templates/index/downloads.html
templates/index/goals.html

*Fixes http://tickets.musicbrainz.org/browse/AB-31.*

AB-31: Documentation update

---

admin/install_hl_extractor.sh
admin/install_server.sh
admin/sql/drop_test_db.sql
bootstrap.sh
manage.py

*Fixes [AB-42](http://tickets.musicbrainz.org/browse/AB-42).*

Updated installation scripts (AB-42)

---

fabfile.py

*Fixes [AB-40](http://tickets.musicbrainz.org/browse/AB-40).*

AB-40: 'git pull' in fabfile

---

templates/data/metadata.html
templates/data/summary-complete.html
templates/data/summary-metadata.html

*Fixes [AB-39](http://tickets.musicbrainz.org/browse/AB-39).*

AB-39: Show recording name and artist in summary page title

---

fabfile.py

*Fixes [AB-45](http://tickets.musicbrainz.org/browse/AB-45).*

AB-45: Added 'install_requirements' command into fabfile

---

acousticbrainz/data/dump.py

I made it so that rows in all tables (not only in `lowlevel`, `highlevel`, and `highlevel_json`) are split up for incremental dumps.
*This should fix [AB-43](http://tickets.musicbrainz.org/browse/AB-43).*

Improved incremental dumps (AB-43)

---

acousticbrainz/views/index.py

Should make it easier to read. :newspaper:

Using thousands separator in numbers in stats block on homepage

---

acousticbrainz/views/index.py
templates/index/index.html

I forgot that there was some math involved in the template. Should work properly this time. :)

Fixed stats on homepage

---

db/test/test_user.py
webserver/login/__init__.py
webserver/login/provider.py
webserver/views/datasets.py
webserver/views/user.py

https://github.com/metabrainz/acousticbrainz-server/commit/d7f9b2571faa4827d49c5825795a9892e0d41a9b#commitcomment-12149066

Minor import improvements

---

db/cache.py
db/data.py
db/stats.py
requirements.txt
webserver/decorators.py
webserver/login/provider.py
webserver/utils.py
webserver/views/api.py
webserver/views/data.py
webserver/views/datasets.py
webserver/views/test/test_data.py

http://tickets.musicbrainz.org/browse/AB-60

Basic Python 3 support for webserver and db packages

---

db/__init__.py
db/stats.py

```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, …
```

Fixed support for non-ASCII MusicBrainz usernames

---

config.py.sample
requirements.txt
webserver/__init__.py
webserver/loggers.py

* Email (SMTPHandler)
* [Sentry](https://github.com/getsentry/sentry) ([Raven](https://github.com/getsentry/raven-python))
:memo:

Added more logging handlers

---

dataset_eval/gaia_wrapper.py

Added docstrings in dataset_eval.gaia_wrapper module

---

webserver/views/data.py

*Fixes http://sentry.roman.zone/sentry/ab-production/group/30/ and http://tickets.musicbrainz.org/browse/AB-49.*

Checking if there are any releases associated with recording in _get_recording_info function

---

webserver/views/data.py

*Fixes http://sentry.roman.zone/sentry/ab-production/group/29/.*

Check if high-level data has been computed correctly before trying to interpret it

---

admin/sql/create_tables.sql
admin/updates/update-8.sql
dataset_eval/evaluate.py
db/dataset_eval.py

I didn't integrate that with the UI yet because #125 changes related part of the interface anyway. I'll add message display after that pull request is merged.
*This is related to [AB-61](http://tickets.musicbrainz.org/browse/AB-61).*

Save messages from exceptions in the dataset evaluator

---

.gitignore
config.py.sample
dataset_eval/evaluate.py
dataset_eval/gaia_wrapper.py
db/dump.py
utils/path.py

:scroll: :honeybee: :honeybee: :honeybee:

History file generation in dataset evaluation process

---

webserver/static/js/eval-jobs-viewer.js

*Related to [AB-61](http://tickets.musicbrainz.org/browse/AB-61).* :boom:

Show status message in evaluation job viewer when error occurred

---

manage.py

*Fixes [AB-75](http://tickets.musicbrainz.org/browse/AB-75).*

AB-75: Fixed database connection initialization in manage.py

---

dataset_eval/gaia_wrapper.py

http://tickets.musicbrainz.org/browse/AB-72

AB-72: Round accuracy to 2dp

---

webserver/login/__init__.py
webserver/login/provider.py

http://tickets.musicbrainz.org/browse/AB-84

Use a class method to create User objects

---

manage.py

Fixes http://tickets.musicbrainz.org/browse/AB-83

Use a wrapper to call sql scripts in admin

---

webserver/static/js/dataset-editor.js

http://tickets.musicbrainz.org/browse/AB-88

AB-88: Deactivate Add recording if the input box is empty

---

webserver/views/data.py

*Fixes http://sentry.roman.zone/sentry/ab-production/group/32/.*

Fix tag retrieval from metadata submitted with recording

---

webserver/templates/navbar.html
webserver/views/login.py

http://tickets.musicbrainz.org/browse/AB-109

AB-109: Login / Logout now redirects you to the page you came from

---

webserver/static/scripts/datasets/class-viewer.js
webserver/static/scripts/datasets/editor.js

[Ticket](http://tickets.musicbrainz.org/browse/AB-110)

AB-110: Link recordings in a class to their AB page

---

webserver/templates/data/summary-metadata.html
webserver/views/data.py

http://tickets.musicbrainz.org/browse/AB-114

AB-114: Replace toma.hk embed with youtube search

---

webserver/templates/data/summary.html

http://tickets.musicbrainz.org/browse/AB-100
What it says on the box

AB-100: Show Key and ChordsDescriptors chord estimates separately

---

webserver/static/styles/main.less
webserver/templates/datasets/accuracy.html
webserver/templates/datasets/index.html
webserver/templates/navbar.html
webserver/views/datasets.py

The "Datasets" link in the navbar does not fit at small browser sizes

AB-57: Add model accuracy page

---

webserver/templates/data/summary-metadata.html

Otherwise it's not working properly on http**s**://acousticbrainz.org pages.

Use HTTPS for YouTube request

---

webserver/static/gulpfile.js

This is pretty much a copy of commit in MusicBrainz server: https://github.com/metabrainz/musicbrainz-server/commit/2c34ea.

Show updates when using gulp-watch

---

admin/sql/create_foreign_keys.sql
admin/sql/create_primary_keys.sql
admin/sql/create_tables.sql
admin/updates/2015-04-18_api_keys.sql
db/api_key.py
db/test/test_api_key.py
db/testing.py
db/user.py
webserver/static/gulpfile.js
webserver/static/scripts/profile.js
webserver/static/styles/theme/boostrap/boostrap.less
webserver/templates/user/profile.html
webserver/views/test/test_user.py
webserver/views/user.py

API key generation

---

admin/sql/create_foreign_keys.sql
admin/sql/create_primary_keys.sql
admin/sql/create_tables.sql
admin/updates/20160617-challenges.sql
admin/updates/20160624-challenges.sql
db/testing.py

This is based on admin stuff and snapshot changes, so look at that first.

AB-120: Schema changes for challenges

---

webserver/forms.py
webserver/templates/datasets/list.html
webserver/templates/macros.html

Continuation of feedback on https://github.com/metabrainz/acousticbrainz-server/pull/165

Clean up html on dataset list

---

webserver/templates/datasets/list.html
webserver/templates/datasets/macros.html

Dataset list improvements

---

db/data.py
db/test/test_data.py

this prevents the highlevel calculation from continually trying to compute files which are (for whatever reason) broken.
We keep offsets consistent - that is, a request to
`mbid/high-level?offset=3`
should return the hl for the file that you get with a request to
`mbid/low-level?offset=3`

Create a highlevel row for empty data

---

webserver/views/datasets.py

http://tickets.musicbrainz.org/browse/AB-96

Tell the user the reason for the validation error when evaling a dataset

---

db/dataset_eval.py
db/test/test_dataset_eval.py
webserver/__init__.py
webserver/views/api/v1/dataset_eval.py
webserver/views/api/v1/test/test_dataset_eval.py

This is associated to: http://tickets.musicbrainz.org/browse/AB-134

Add an API for getting pending jobs for a user

---

webserver/views/api/v1/dataset_eval.py
webserver/views/api/v1/test/test_dataset_eval.py
webserver/views/api/v1/test/test_datasets.py

This is related to http://tickets.musicbrainz.org/browse/AB-144

API endpoint for getting details of a job

---

webserver/views/api/v1/core.py
webserver/views/api/v1/dataset_eval.py
webserver/views/api/v1/test/test_core.py
webserver/views/api/v1/test/test_dataset_eval.py

This is related to http://tickets.musicbrainz.org/browse/AB-147

Get multiple recordings

---

webserver/templates/navbar.html

This also fixes [AB-140](http://tickets.musicbrainz.org/browse/AB-140).

Make navbar more compact by moving some items into dropdowns

---

db/dump.py

Fix docstring of data dump function

---

admin/sql/create_db.sql
admin/sql/create_test_db.sql

See [LB-244](https://tickets.metabrainz.org/browse/LB-244) for details.

Use NOSUPERUSER instead of NOCREATEUSER

---

db/dataset.py
db/test/test_dataset.py
webserver/static/scripts/datasets/class-viewer.js
webserver/static/scripts/datasets/editor.js
webserver/views/datasets.py
webserver/views/test/test_data.py
webserver/views/test/test_datasets.py

Removed the criteria of being logged in for viewing the recording info from datasets.

AB-290 : Viewing the recording information of a dataset or a snapshot requires being logged in

---

docker/jenkins-test.sh
pytest.ini
requirements.txt

Totally a work in progress, I'm not sure about having a Dockerfile.test too.

AB-323: Setup Jenkins automated testing for PRs

---

INSTALL.md
dataset_eval/evaluate.py
db/dump_manage.py
docker/docker-compose.dev.yml
hl_extractor/hl_calc.py
hl_extractor/job_calc.py
manage.py
requirements.txt
worker_manage.py

This will automatically create the app and wrap commands in a flask context, which will connect to any required services (e.g., database, cache)

Use FlaskGroup to create the CLI interface

---

utils/dataset_validator.py
utils/test/test_dataset_validator.py

Changed the range check of higher value from MIN to MAX.

AB-330: Class name range check

---

requirements.txt
webserver/__init__.py
webserver/views/test/test_index.py

Also, add a test to ensure that it works

Initialize Flask-DebugToolbar correctly

---

db/dump_manage.py
manage.py
webserver/__init__.py
worker_manage.py

https://tickets.metabrainz.org/browse/AB-333

AB-333: Use 'FlaskGroup' for creating CLI interface in 'dump_manage.py'

---

requirements.txt
webserver/admin/forms.py
webserver/forms.py

Tested with tests, and some general clicking around in the website

Upgrade python dependencies

---

db/import_mb_data.py

Now the logs give us the information on what data is being fetched and what and how much data is getting inserted into their corresponding tables.

AB-342: Improve logging during MusicBrainz data import

---

docker/consul-template.conf
hl_extractor/profile.conf.in.ctmpl

Add consul template for hl_extractor profile

---

db/dump.py
db/test/test_dump.py
manage.py
webserver/__init__.py

Also, add a command to manage.py to update_sequences, if needed.

AB-93: Update sequences in the db after an import of some data dump

---

db/dump.py
db/test/test_dump.py
requirements.txt
webserver/templates/index/downloads.html

Use one query for dumping lowlevel json

---

requirements.txt

Flask is keep making changes each version and in order not to break some things with outdated material, it is updated to its latest version

Update Flask to the latest version

---

docker/Dockerfile.dev
docker/docker-compose.dev.yml
hl_extractor/hl_calc.py
hl_extractor/job_calc.py

This is so that changes in the code can be reflected immediately in the containers without having to rebuild them

Add working directory as volume to all docker containers

---

consul_config.py.ctmpl

Point to our own redis service

---

webserver/decorators.py
webserver/static/scripts/datasets/class-viewer.js
webserver/static/scripts/datasets/editor.js
webserver/static/scripts/datasets/eval-jobs-viewer.js
webserver/views/datasets.py
webserver/views/test/test_datasets.py
webserver/views/user.py

Added a new decorator @api_login_required in webserver/decorators.py for api endpoints which return JSON

AB-318: Return HTTP401 on API endpoints if the user is not logged in

---

CONTRIBUTING.md

This pull request improves the clarity of the git workflow for AcousticBrainz and creates a section on bug tracking.
- Include information about using the ticketing system to track and solve issues.
- Also improve git workflow section by including branching and use of git rebase.

Describe bug tracking and improve git workflow in CONTRIBUTING.md

---

requirements.txt
webserver/views/api/v1/test/test_core.py
webserver/views/api/v1/test/test_dataset_eval.py
webserver/views/api/v1/test/test_datasets.py

Upgrade dependencies

---

webserver/forms.py
webserver/static/styles/theme/boostrap/forms.less
webserver/templates/datasets/import.html
webserver/views/datasets.py
webserver/views/test/test_datasets.py

**AB-390: Datasets uploaded with csv import are always made public**
This feature gives users an option to create a dataset in public or private mode when datasets are uploaded with CSV import.

AB-390: Datasets uploaded with csv import are always made public

---

dataset_eval/artistfilter.py
db/__init__.py
db/dump_manage.py
hl_extractor/hl_calc.py
hl_extractor/job_calc.py
manage.py
webserver/__init__.py

https://tickets.metabrainz.org/browse/AB-67
https://tickets.metabrainz.org/browse/AB-366
Use `flask.current_app.logger` instead of print

AB-67, AB-366: Use the flask logger instead of print for informational messages

---

webserver/views/api/v1/core.py

Needed for https://github.com/metabrainz/musicbrainz-server/pull/1578

Add tonal.key_strength to list of allowed ll fields to request

---

webserver/templates/index/downloads.html

FTP support in browsers is being dropped, so switch to http

Move download links to http

---

.github/workflows/build-and-push-image.yml

See https://github.com/metabrainz/listenbrainz-server/pull/1498

Use tag to set GIT_COMMIT_SHA

---

webserver/views/api/v1/core.py

AB-460
This was requested by an API user

AB-460: Add tonal.chords_changes_rate to allowed lowlevel features

---

webserver/static/scripts/datasets/eval-jobs-viewer.js
webserver/views/datasets.py

In the case that someone wants to use the model file that they created,
provide a link that allows them to download it so that they can compute
their own hl data using gaia
Inspired by https://twitter.com/johnpaulvaughan/status/1412324504764698627

Add link to download a dataset evaluation's history file

---

admin/updates/20190619-similarity.sql
admin/updates/20190716-similarity-eval.sql
config.py.example
consul_config.py.ctmpl
db/similarity.py
similarity/index_model.py
similarity/manage.py
webserver/__init__.py
webserver/templates/data/summary.html

Issues found while running similarity on beta.

Similarity bug fixes and improvements
