metabrainz/acousticbrainz-server

- manage.py
It makes possible importing incremental dumps after database is initialized with `init_db`.
> Separate data importing command in manage.py

- server.py
Before that it was kind of useless, same goes for `DEBUG` parameter in config file. Debug mode was always on. :confounded:
> Fixed `debug` argument in server.py

- acousticbrainz/views/datasets.py
- acousticbrainz/views/datasets_test.py
It is used in the dataset viewer. I thought it was unused and removed it in 6ca97ec07806b8f186768c6fe9ed8311a3e223b6. :bomb:
> Added back datasets.view_json view

- webserver/errors.py
- webserver/exceptions.py
- webserver/templates/navbar.html
- webserver/test/test_api.py
- webserver/views/api.py
Fixes AB-90: http://tickets.musicbrainz.org/browse/AB-90
We use a flask pattern from
http://flask.pocoo.org/docs/0.10/patterns/apierrors/
to raise a specific api error and return a json response in the
error handler.
We add two more routes to catch /anything/low-level and .../high-level
so that we can also return json for invalid uuids, not just missing
ones.
> AB-90: Return a json error message for API endpoints

- webserver/templates/datasets/accuracy.html
I have not tested a rendered HTML yet. 
We should also host ```rosamerica_mp3_filelist.yaml``` file somewhere, and link to in in the description. The same can be done for the rest of music collections to provide at least partial information about the tracks.
> Add dataset information for default classifier models

- .gitignore
- fabfile.py
- pytest.ini
- requirements.txt
It behaves pretty similar to nose, and doesn't make much difference in our case.
To run all tests just use `py.test` command.
> Use py.test as a test runner

- hl_extractor/hl_calc.py
Whenever we return early from the hl calculation file we need
to make sure that we remove any temporary files that we created.
This includes:
- input (lowlevel) file if we fail to write data to it
- input and output (highlevel) file if we fail to run the extractor
Tests:
Ran manually with a `streaming_extractor_music_svm` file which was not `+x` (failed with `OSError`), and a dummy script which returned `1` (failed with `subprocess.CalledProcessError`). Without these changes, tmp files remained, with the changes they were cleaned up.
I'm not sure of the best way to test the `IOError`s for the input and output file. If these open/reads fail I think we have more serious problems on the server
> Delete temporary files if hl calculation fails

- admin/install_hl_extractor.sh
Removed ‘—download’ option from waf configure
Changed the name of the essentia extrator from
streaming_extractor_music_svm to essentia_streaming_extractor_music_svm
and changed the destination dir to hl_etractor
> Gaia Config and essentia extractor

- requirements.txt
https://github.com/metabrainz/acousticbrainz-server/pull/216 again
Used in oauth login with musicbrainz, broken since
newhost setup. Also reported in AB-130 but not correctly
fixed the first time around
I actually tested this on a trusty VM this time around (same as spike), and I got the error without the package, and no error with it.
> Use an https client which checks SSL certificates

- webserver/views/api/v1/core.py
- webserver/views/api/v1/test/test_core.py
Theoretically it should work... I haven't tested it yet though
Edit: tested, the modified test passes only with the change in core.py
> Add crossdomain header for /api/v1/low-level endpoint (AB-295)

- webserver/views/api/v1/core.py
- webserver/views/api/v1/test/test_core.py
GET request for bulk low-level data was failing when any single
one of the MBIDs were not present in the database. These entries
are now put into an error field appended to the fetched data for
existing recordings.
Relevant Jira ticket: https://tickets.metabrainz.org/browse/AB-296
> Fix bulk low-level get request with non-existent MBID

- CONTRIBUTING.md
An attempt at starting detailed contributing documentation so that we don't have to keep repeating ourselves. Based a little bit on discussion in IRC, on the Forums, and things that I've noticed over the last few years.
My preference is to get this merged as quickly as possible, and iterate on changes as issues come up; rather than spending a long time discussing updates in this PR.
I'm open to corrections of things which are obviously wrong and updates of things that we currently do.
We should also consider if this is a good place to have these guidelines. CB has a nice set of documentation online (http://critiquebrainz.readthedocs.io/contributing.html). We could also replicate this.
> Add detailed contributing documentation

- admin/install_web_server.sh
- admin/setup_app.sh
We install gaia and its python bindings into /usr/local but use a venv for the webapp. Add gaia to the venv path so that we can run the dataset classifier inside vagrant.
Also add libssl-dev which was causing requirements to fail to install, and upgrade from node 5 to 6 because of out-of-supportness
> Ensure that gaia is available in the virtualenv pythonpath

- dataset_eval/gaia_wrapper.py
The preprocessing value is important to be able to reproduce the results
of the classification, so don't remove these parameters before storing
them
> Don't pop preprocessing and classifier off of params dictionary

- package.json
based on output of `npm outdated`. I left react, jquery, lodash, and highcharts
because they were a major version upgrade. Tested by running gulp
and checking the dataset editor/viewer pages.
> Upgrade javascript dependencies

- dataset_eval/artistfilter.py
This is a:
**Problem:**
While dataset_evaluation on preference: ArtistFilter, we get an error: 
```
dataset_evaluator_1  | sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "mbid" does not exist
dataset_evaluator_1  | LINE 1: SELECT mbid::text, data->'metadata'->'tags'->'musicbrainz_ar...
dataset_evaluator_1  |
```
In https://github.com/metabrainz/acousticbrainz-server/blob/master/dataset_eval/artistfilter.py#L146, an sql query is trying to get the 'mbid' column which wasn't present in the lowlevel table, instead gid column is present there which should be fetched.
**Solution** 
I have renamed `mbid `to `gid` in `dataset_eval/artistfilter.py`, so that whenever any user tries to evaluate a dataset with the preference `"Artist filter"`, the query won't direct to the wrong …
> AB-322: Renamed mbid to gid from sql query

- db/dataset_eval.py
- db/exceptions.py
- db/test/test_dataset.py
- utils/test/test_dataset_validator.py
- webserver/views/api/exceptions.py
- webserver/views/api/v1/datasets.py
- webserver/views/api/v1/test/test_core.py
- webserver/views/api/v1/test/test_datasets.py
- webserver/views/datasets.py
pytest was reporting warnings of the form:
```
db/test/test_dataset.py::DatasetTestCase::test_update_dataset_meta_badmeta
/code/db/test/test_dataset.py:124: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
self.assertEqual(e.message, "Unexpected meta value(s): badkey")
```
due to `exception.message` being deprecated. Move all the cases where we use this to `str(exception)`, which is the new accepted way. This gets the contents of the first argument passed to the exception handler.
>  Replace use of deprecated Exception.message with str(exception)

- package.json
- webserver/static/scripts/stats.js
Upgrade JS dependences as listed by `npm outdated`
Tested that gulp still generates the bundle as expected, and js parts of the site work.
Leaving React for now, as it will require code changes to do the upgrade.
> Upgrade JS dependencies

- README.md
- default_config.py
- docker/docker-compose.dev.yml
- requirements.txt
- webserver/__init__.py
Setup in AB to access the MB database. The metabrainz/musicbrainz-test-docker image is use to add the container.
> AB-334: Setup to directly access MusicBrainz Database

- README.md
- db/import_mb_data.py
- manage.py
* To initialize the musicbrainz database:
`./develop.sh run --rm  webserver python2 manage.py init_mb_db`
* To start the import:
`./develop.sh run --rm  webserver python2 manage.py import_musicbrainz_db`
> AB-340: Import MusicBrainz data in a separate musicbrainz schema in AB database

- admin/sql/drop_musicbrainz_schema.sql
- manage.py
Add a force option to init_mb_db:
* That drops the musicbrainz schema if exists, along with all the tables and keys.
* And then recreates the schema structure.
>  AB-344: Add a force option to manage.py init_mb_db

- db/import_mb_data.py
- default_config.py
Add a variable for the number of recordings to fetch at a time in default_config.py file to import the MB metadata.
> AB-343: Move number of recordings fetched per batch into config.py

- db/import_mb_data.py
Some tables viz. `artist_credit` and `area` are dependent on other tables for inserting their data. This PR is to get the data for those left over tables which weren't included in [PR #272 ](https://github.com/metabrainz/acousticbrainz-server/pull/272)
> AB-349: Get data for more foreign key referenced tables

- docker/docker-compose.jenkins.yml
- docker/docker-compose.test.yml
- docker/jenkins-test.sh
- test.sh
Disable fsync in postgres to make tests run faster
Mount source code into the test volume so that you don't have to build the image each time you test
Add the ability to pass arguments to pytest from test.sh
> Make testing faster

- admin/sql/create_musicbrainz_tables.sql
- config.py.example
- db/data.py
- db/import_mb_data.py
- db/testing.py
- manage.py
- musicbrainz_importer/apply_replication_changes.py
This PR contains scripts to apply replications packets to musicbrainz schema in AcousticBrainz db to keep it updated with the actual Musicbrainz db.
> AB-350: Update musicbrainz schema whenever actual MusicBrainz database is updated

- docker/consul-template.conf
- webserver/__init__.py
> Fix Config loading code

- db/dump.py
- db/dump_manage.py
- db/test/test_dump.py
- manage.py
Instead of dumping the entire lowlevel_json and highlevel_model tables into a single file, I've split it into multiple files. 
This is very similar to how we do it in LB. We keep dumping more rows into a file until the size of the file becomes more than 10 GB.  
We then add these files to the archive and remove them from temporary storage.
>  Limit size of files while dumping lowlevel_json 

- docker/docker-compose.dev.yml
- docker/docker-compose.jenkins.yml
- docker/docker-compose.test.yml
To bring us in line with what's in production.
Also use a named volume to store postgres data.
Also remove hlextractor and dataset eval from test docker-compose, which we don't need to run. Their image is shared with webserver, so if we have specific tests we can run in the webserver container too.
> Upgrade to Postgres 10 in docker-compose

- db/dump.py
- manage.py
Dumps were being created by using `TarFile.add`, passing in an entire directory. This didn't give us control of the order in which files were added to the dump. Now, explicitly add each file to the archive as we dump the table in the defined order.
This allows us to import dump files even if fk constraints are present, because all required rows are added in the right order.
Also fix dataset dumps to ensure that they dump in an order that can be imported with fk constraints
Include a small fix to the highlevel_model dump to include all rows
Fix a bad merge introduced by the combination of the dataset dumps and #299
>  AB-367: Create dump archive in specific order

- webserver/templates/data/data.html
- webserver/templates/navbar.html
I mentioned the readthedocs site on the API/Data page, instead of listing information about the API there, as requested in AB-373
> AB-373 Changed API/Data Navigation link to readthedocs

- docker/docker-compose.dev.yml
Because docker re-creates containers on restart, including the
default user's home directory, history from commands like psql
and ipython are lost every time we restart a container.
Store the home directory in a volume so that the history is
shared between runs.
> Mount root home as a volume to preserve command history

- README.md
Make it clearer what steps are required for first-time configuration and setup, and what steps are needed during development
I'm not sure if the steps about login/oauth should be moved to setup - it's technically not required for first time setup, so I'm tempted to leave it as-is.
> Alter README to improve separation between setup and development

- docker/docker-compose.dev.yml
- manage.py
The runserver command was broken by a flask upgrade in #308, causing
it to lose the app context when the reloader restarted the app.
Copy the flask.cli.run_command command to our manage.py so that it acts
like `flask run`, including the debugger and reloader behaviour.
Ensure that we also reload on changes to config.RELOAD_ON_FILES
Fixes AB-327
> Improve runserver command to work with reloader and debugger

- webserver/views/api/v1/core.py
- webserver/views/api/v1/test/test_core.py
This is a...
**Present Case:** 
We don't have any feature which provides high-level data with one request for many `recording ids`.
**Solution:**
I have added a feature through which we can fetch JSON documents for a list of MusicBrainz recording IDs for high-level data.
The user can construct the endpoint (Suppose for a list of 3 MBIDs) for high-level data by:
GET https://acousticbrainz.org/api/v1/high-level?recording_ids=mbid;mbid;mbid
> AB-21: Get high-level data for multiple recordings with one request

- db/dataset_eval.py
- db/test/test_dataset_eval.py
- webserver/views/datasets.py
This is a...
**Present case:** 
We are not able to validate the structure of the dataset before submitting it for evaluation.
**Solution:**
Validating the dataset previously and show the user the warning before the user has the option to submit the dataset for evaluation and validating dataset contents after submitting the dataset.
> AB-327: Validate dataset structure before submitting for evaluation and dataset contents after.

- docker/jenkins-test.sh
We introduced an error in this commit (the --remove-orphans flag).
We added 2 `ls -lR` in this commit, which results in a huge page output when listing node modules. I've removed one and left just the one in the container. I'm not sure if this is still necessary, but it could be useful.
Also use set -x to show commands before they're run.
Use `docker version` instead of `docker --version`, to show the client and server versions of docker, for debugging.
> Revert some unneeded changes introduced in 4f3589e881

- utils/dataset_validator.py
- utils/test/test_dataset_validator.py
- webserver/static/scripts/datasets/editor.js
There was an existing error where we were not rendering the .error property, causing a react exception.
> Only render the error message if it exists

- admin/sql/create_indexes.sql
- admin/updates/20190227-statistics-indexes.sql
- db/stats.py
- db/test/test_stats.py
- manage.py
We had an issue where a compute_stats run must have skipped writing a single row, as a result, the stats page couldn't find the value for this date.
Add all rows in a single transaction so that if there is any problem writing any one of them, we're not left in an inconsistent state
Perform an additional sanity check after computing stats to ensure that we're not left in this state any more
If a value is missing when rendering the stats page, ignore it instead of raising an error
Only return a stats value for each day to reduce the size of the returned js file 24x (5MB->200K), and add some indexes to make this process faster.
This PR adds a new SQL update file which creates some indexes, `admin/updates/20190227-statistics-indexes.sql`, this should be run after deployment.
> AB-376: Add all stats rows in a single transaction

- Dockerfile
- docker/push.sh
Define the deploy_env ARG in all stages
From the documentation:
https://docs.docker.com/engine/reference/builder/#scope
An ARG instruction goes out of scope at the end of the build stage where
it was defined. To use an arg in multiple stages, each stage must
include the ARG instruction.
Also fix a syntax error in push.sh, missing a continuation line
> Docker args

- db/dataset.py
- db/test/test_dataset_eval.py
This makes it easier to reason about tests, but also makes sense
to ensure that users see items in the same order that they added
them originally to the dataset
> Preserve order of recording ids when removing duplicates

- db/dataset_eval.py
**Code Improvement** 
Issue : The method get_pending_job in dataset_evel.py was running a query to return job id's which had status as Pending, which was then passed to get_job(job_id) to return information about these jobs
improvement : instead of running two separate queries for one task, the task is performed by a single query, and get_pending_job returns same data as the method get_job(job_id).
> Resolved TODO: get_next_pending_job now returns same data as get_job

- add_submission_offsets.py
- admin/sql/create_tables.sql
- admin/updates/20190508-submission-offsets-1.sql
- manage.py
- submission_offsets.py
This will allow for us to populate the submission offset but the field 
will be null for recordings that are submitted during the process, 
allowing us to catch and update them in the next step. Note that the
offset column will only exist in the lowlevel table.
Uses a subquery with a window function to calculate the offsets for all
existing entries, then update the submission_offset column in lowlevel 
with the results.
> AB-406 Step 1: Offset migration for existing submissions

- requirements.txt
1.9 and lower reference a version of mbdata which is no longer on pypi
> Upgrade brainzutils to 1.11

- docs/api.rst
- webserver/views/api/v1/core.py
- webserver/views/api/v1/test/test_core.py
This number tries to seek a balance between a good number of items and the time taken to respond to the query. Tests show that 1 item takes about .3s while 25 take .8s and 50 takes over 1.5s
Also document this number in the API docs.
> Set the maximum bulk query number to 25 and add documentation

- db/testing.py
- webserver/forms.py
- webserver/templates/datasets/import.html
- webserver/testing.py
- webserver/views/datasets.py
- webserver/views/test/test_datasets.py
- webserver/views/test_data/test_dataset.csv
- webserver/views/test_data/test_db.csv
This pull request addresses the issues noted in ticket AB-387
https://tickets.metabrainz.org/projects/AB/issues/AB-387?filter=allopenissues
- alter `_parse_dataset_csv(file)` in `webserver/views/datasets.py` to
handle dataset and class descriptions on any line of csv file
- csv line format for dataset description: 
`description,description of dataset dataset`
- csv line format for class description: 
`description:class1,description of class 1`
- `_parse_dataset_csv(file)` returns `[dataset_description, classes]`
where dataset_description is description of entire dataset and classes
is a list of all class dictionaries with structure:
```    
{'recordings': [mbid1,...,mbidn], 
'description': 'class description', 
'name': 'class_name'}
```
- small change to `db/dataset.py` function …
> Include dataset and class descriptions in CSV for import/export - AB-387

- db/data.py
- db/test/test_data.py
- webserver/__init__.py
- webserver/views/api/legacy.py
- webserver/views/api/test/test_legacy.py
- webserver/views/api/v1/core.py
- webserver/views/api/v1/test/test_core.py
https://tickets.metabrainz.org/browse/AB-411
With the changes in AB-406 we introduced a bug where GET for a single item failed because postgresql returned mbids in lower-case and we tried to use the upper/mixed case value that was passed as a parameter.
Additionally, the Flask-uuid extension only accepts lower-case uuids by default, meaning that some of our API endpoints returned HTTP404 when presented with upper-case MBIDs, even if they existed in the database.
Convert all uuids to lower-case when returning them, and document this. Accept API queries using upper-case uuids.
I made no changes to the internal datasets api because we always use uuids returned from the api/postgres here, which are always lower-case.
> AB-411: Fix exceptions when uuids have upper-case characters

- admin/sql/create_tables.sql
- admin/updates/20190606-highlevel-model-mappings.sql
- db/data.py
- db/test/test_data.py
- webserver/templates/data/summary.html
- webserver/templates/datasets/accuracy.html
- webserver/views/api/v1/core.py
- webserver/views/api/v1/test/test_core.py
- webserver/views/data.py
A continuation of #330 with a few additional changes to improve the code flow and number of queries that we make.
Also add some more mappings and improve the way that we display this data on the summary page.
> AB-91: Map model classes to more meaningful labels

- webserver/views/api/v1/datasets.py
- webserver/views/api/v1/test/test_datasets.py
https://tickets.metabrainz.org/projects/AB/issues/AB-417
We had no tests for dataset delete, and so didn't know that the delete endpoint used the incorrect method to get the dataset before deleting it.
> AB-417: Correctly delete datasets

- docs/dev/deployment.rst
- docs/index.rst
With the introduction of the `production` branch
and https://beta.acousticbrainz.org,
it'd be good to document the usage of the `master`
and the `production` branch.
This is a sister PR to https://github.com/metabrainz/guidelines/pull/12 and should be merged after that.
> Add documentation about deployment practices

- webserver/views/data.py
- webserver/views/test/test_data.py
https://tickets.metabrainz.org/projects/AB/issues/AB-418
We were only formatting minutes and seconds of a length, not hours. Add them in
> AB-418: Format track lengths greater than an hour

- webserver/views/datasets.py
- webserver/views/test/test_datasets.py
https://tickets.metabrainz.org/projects/AB/issues/AB-419
The csv module in python 2 requires that all values to it are ascii.
Explicitly convert dataset description, class names, class descriptions before adding them to the csv.
Don't convert uuids because they're valid ascii
I tested csv import with unicode text in the csv file and it worked fine
> AB-419: Encode unicode text when exporting dataset csv

- webserver/__init__.py
The redirects are permanent, so the correct code should be 301 while flask defaults to 302.
> Specify status code to 301 for http requests redirect

- webserver/views/api/legacy.py
- webserver/views/api/test/test_legacy.py
- webserver/views/api/v1/core.py
- webserver/views/api/v1/test/test_core.py
Postgres requires that uuids are all lower-case, and formatted with hyphens in the correct locations, but uuid.UUID accepts values missing hyphens or with them in non-standard locations. Use str(uuid.UUID(val)) to always normalise these values before passing to postgres.
> AB-432: Allow badly-formatted MBIDs, but normalise them before use

- admin/sql/create_tables.sql
- admin/updates/20200428-alter-dataset_class-schema-description-not-null.sql
- db/dataset.py
- db/test/test_dataset.py
- webserver/views/datasets.py
- webserver/views/test/test_datasets.py
Based on the [AB-436](https://tickets.metabrainz.org/browse/AB-436?jql=project%20%3D%20AB%20AND%20status%20%3D%20Open%20AND%20labels%20%3D%20good-first-bug) jira, the following issues are now fixed:
- When uploading a dataset via a CSV file, if the class name description is empty during the submission, the corresponding value that is stored into the DB is not anymore a null value but an empty string `''`.
- The `defaultdict(lambda: {"description": None, "recordings": []})` had to change to `defaultdict(lambda: {"description": '', "recordings": []})` class dictionary declaration inside the _"webserver/views/datasets.py", line 338, `_parse_dataset_csv()`_ function, in order to change the `key/value` class description of the class dictionary declaration.
- The same submission logic is fixed …
> AB-436: Fix issues. datasets' class descriptions accept empty strings

- Dockerfile
- docker/docker-compose.jenkins.yml
- docker/jenkins-test.sh
- docker/push.sh
This was a little bit more involved than I had hoped, because npm installs things in the working directory... Because of this I had to make the `acousticbrainz` user earlier, and then `COPY --chown` everywhere, and use `USER` to switch between users. Now, everything in /code is owned by acousticbrainz.
Some upsides: now, everywhere that you run this, it's running as a non-privileged user!
Some downsides
* now you can't run `pip install` in a shell if you temporarily want to install something while developing. Should we revert back to running as root for this?
* Running in dev on a linux host, we've still got the issue where commands are being run as uid 901, and therefore files which are created by it can't be read/deleted by the user on their host without `sudo chown` magic
@paramsingh …
> AB-437: Make files in /code owned by the acousticbrainz user

- utils/dataset_validator.py
- utils/test/test_dataset_validator.py
- webserver/errors.py
- webserver/views/api/v1/datasets.py
- webserver/views/data.py
- webserver/views/datasets.py
- webserver/views/test/test_datasets.py
- webserver/views/test_data/test_dataset_utf8.csv
https://tickets.metabrainz.org/browse/AB-420
There were 2 issues here
* Unicode text in the mbid field of an uploaded dataset failed to parse
* Unicode text in the message of an exception failed to render because we used `str(exp)`
I've changed some of the instances where we rendered exceptions to use six and ensure that this message is always unicode text. I didn't change all cases of str(exp) because many of these exceptions use string constants in the server codebase, and all examples that I could find use only ascii text. What's more, I think that these problems will go away when we move to python 3, so I don't think we need to spend time on changing these if they're not causing problems.
> AB-420: allow unicode characters in MBIDs when uploading a dataset

- db/data.py
- db/test/test_data.py
- db/test_data/lowlevel_select_features_response.json
- docs/api.rst
- utils/container_utils.py
- utils/remove_duplicates.py
- webserver/views/api/v1/core.py
- webserver/views/api/v1/test/test_core.py
This feature allows users to select only a subset of the lowlevel data available when they do not require the whole file, and should help to reduce loads as a result. It makes this possible with the following changes:
- Create an endpoint, get_many_select_features which takes the required features as a parameter.
- Parse the features to get a string of paths that access different features of lowlevel.data.
- Query for these features in a similar fashion to other bulk get methods.
> AB-404: Endpoint for users to select specific lowlevel features

- db/data.py
- hl_extractor/hl_calc.py
- hl_extractor/test/test_data/known_file
- hl_extractor/test/test_hl_calc.py
This is the second part of AB-439. Once approved, we can merge it into #378 and then merge that.
The slowst part of the highlevel extractor is loading the model files. However, the the extractor can take multiple lowlevel files as input and will output multiple highlevel files. This means that it only loads the models once, and the runtime for 20 lowlevel files will be almost 20x faster than running the binary 20 times in a row. 
Add some tests for the main part of the hl extractor
Use the logger instead of print statements. Manually get the logger in the main method that is run in a thread, to prevent flask threading issues.
One final thing I want to do before merging these 2 items into master is to set up a test server with a handful of documents and run both HL extractors, ensuring …
> AB-349 (II): Process multiple documents with the highlevel extractor at once

- db/data.py
- hl_extractor/hl_calc.py
- hl_extractor/test/test_data/known_file
- hl_extractor/test/test_hl_calc.py
- requirements.txt
https://tickets.metabrainz.org/projects/AB/issues/AB-439
https://tickets.metabrainz.org/projects/AB/issues/AB-440
This is the first part of AB-439 and AB-440. I'm going to split it up into a few different PRs to make it easier to follow the evolution of the changes.
This specific change moves from manual thread pool management to using [concurrent.futures](https://docs.python.org/3/library/concurrent.futures.html). For now we use a python2 backport. This won't be needed in python 3. This makes the queue submission code much simpler and easier to extend.
There's one difference to the way we load the thread pool in this new version. We load all document to the pool, but when it starts to run out we don't fill it up again. e.g. if we have 10 threads, and we've processed 90 and are on the …
> AB-439: Use concurrent.futures to manage threading in hl extractor

- webserver/forms.py
AB-448
If the feature flag is disabled, the HTML form doesn't include this field, so we have to ignore the pre_validate() method, which checks if the value is one of the valid choices (as there is no value submitted with the form, it's invalid).
Explicitly perform this check if the feature flag is enabled.
> AB-448: Only validate filter_type if FEATURE_EVAL_FILTERING is True

- docker/uwsgi/uwsgi.ini
This does nothing except fill up tens to hundreds of gigabytes of logs,
and isn't needed.
UWSGI logs each request, in the form 
> [pid: 343|app: 0|req: 678/3082] 93.213.240.171 () {38 vars in 637 bytes} [Mon Feb  1 15:42:51 2021] GET /a5a41a8a-9eb8-4d89-b831-c3b3636ee55c/low-level => generated 52243 bytes in 14 msecs (HTTP/1.1 200) 10 headers in 411 bytes (1 switches on core 0)
This fills up docker logs (tens to hundreds of GB), and we don't use any of it
Disable uwsgi request logging (yes, the config option is 'disable-logging', but this is only request logging, not generic logging)
> Disable uwsgi request logging

- Dockerfile
- requirements.txt
Once metabrainz/brainzutils-python#45 is merged, BU will use open ended versions. To make sure we use desired versions, pin the versions in downstream projects.
The BU PR must be merged before this PR and the requirements.txt must be updated to use the new release of BU. The same is applicable for the dataset hoster.
> Pin package versions

- config.py.example
- requirements.txt
- webserver/__init__.py
Upgrade to new version of brainzutils which uses sentry-sdk instead of raven.
Remove unused email logging configuration.
Tested manually by setting the DSN and causing an exception to be raised
> Upgrade brainzutils and sentry-sdk

- consul_config.py.ctmpl
These flags were added in https://github.com/metabrainz/acousticbrainz-server/pull/257 but we forgot to add those to consul config.
> Add missing consul config flags

- Dockerfile
- requirements.txt
On github actions, sometimes we compile on a machine that has avx512
available, but this isn't available on our prod machines. Force
something lower.
> Upgrade annoy,  force a CPU architecture to avoid unavailable extensions

- config.py.example
- consul_config.py.ctmpl
- similarity/index_model.py
Annoy 1.17 can build indexes using multiple threads, so this should speed up build time.
> Specify number of threads to use when building annoy index

- webserver/errors.py
AB version of https://github.com/metabrainz/listenbrainz-server/pull/1577
Note that because AB is still running python 2 it's using an old version of BU which will still return a plain text error response for now.
When we merge #403 with a new version of BU this handler will start working.
> Add TooManyRequests error handler

- webserver/__init__.py
> Exempt legacy api from CSRF protection

- webserver/views/api/v1/core.py
- webserver/views/api/v1/test/test_core.py
An extra ; in the query parameter would cause us to try and validate `''` as a valid UUID, which would fail. Silently skip these cases
> Skip a recording_ids bulk param if there is an empty mbid

- config.py.example
- db/data.py
- db/test/test_data.py
- webserver/views/api/legacy.py
- webserver/views/api/v1/core.py
We allow duplicate submissions, but over a certain number it doesn't really make sense to keep them.
This is also causing us to quickly run out of disk space.
After 10 submissions of the same MBID, stop accepting submissions
> Don't accept submissions if too many duplicates are received

- db/dump.py
- db/dump_manage.py
* Don't double-encode lowlevel json
* Don't include part number in tar location
With a part file acousticbrainz-lowlevel-json-20220616-0.tar.zstd, we want the files inside to be in a subdirectory
acousticbrainz-lowlevel-json-20220616/
so that when many part files are uncompressed in the same directory they all fill in the same directory structure.
* Update subdir location
With 30m data files and a subdirectory structure of `m/mb/mbid-offset.json` we end up with 30m/256 = 117000 files per directory, which could cause some problems in some filesystems or with incorrect use of `ls`.
Instead, save as `mb/i/mbid-offset.json`, resulting in ~7000 items per directory
* Generate a sample data dump (lowlevel, highlevel json) with only 100,000 items
* Add a lowlevel individual feature dump for …
> Dump cleanups
